## 1. nest-api-blog
blog接口服务

## 2. 变量定义

@base=http://localhost:3000/v1

## 3. 接口列表

### 2.1 待补充
GET {{base}}/

### 2.2 创建访问
POST {{base}}/visit/pv
Content-Type: application/json

{
  "pagePath": "string, 必选, 页面"
}

### 2.3 获取访问
GET {{base}}/visit/list